name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # Set your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # Set your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build  # If you have a build script in your package.json

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tianyuproject'  # Set your Azure App Service Name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Set your Azure publish profile secret
        package: '.'  # Path to your packaged app code

